llm: gpt-3.5-turbo-0613
random_seed: 69847
job_name: idigbio-sample
qa:
  occurrence:
    input: results/idigbio-sample/input/all-shuffled-69847.tsv
    shuffle: true
    query_limit: 40000
    batch_size: 100
  taxonomy:
    input: results/idigbio-sample/input/taxonomy-qa.tsv
    shuffle: false
    query_limit: 0
    batch_size: 100
results:
  notebook: process-occ-gpt.py.ipynb
