# gpt-3.5-turbo-0613
# gpt-4-1106-preview
# llama2-7b-chat
llm: llama2-7b-chat
command: python3 ~/biodiversity-llms/scripts/nlp/qa.py
input: resources/test-data.tsv
output_dir: results/test-job
args:
  - --max-tokens 100
  - --timeout 10
  - --num-responses 2
shuffle: true # Whether to submit queries sequentially or shuffled
batch_size: 1
query_limit: 1 # Set to 0 to run all queries, otherwise only run this many (x the number of query templates)
query_fields:
  - species
query_templates:
  - How do {species} know?
query_suffix: Explain it to me like I'm 5.
